version: '3.3'

services:

    nginx:
        build:
           context: ./nginx
           dockerfile: Dockerfile
        ports:
            - '1935:1935'
            - '127.0.0.1:1234:80'
        volumes:
            - './nginx/html:/usr/local/nginx/html'
            - 'dash:/opt/dash:z'
            - './data/uploads:/opt/uploads'
        restart: unless-stopped
        logging:
            driver: "none"
        depends_on:
            - nodejs
            - php
        networks:
            - backend

    php:
        image: php:7-fpm
        volumes:
            - './nginx/html:/usr/local/nginx/html'
            - '/home/hllm/poi/s1:/opt/injest/'
            - 'dash:/opt/dash:z'
            - './data/uploads:/opt/uploads'
            - 'convert:/opt/convert:z'
        networks:
            - backend

    nodejs:
        build:
            context: ./nodejs
            dockerfile: Dockerfile
        networks:
            - backend
    
    alpine:
        build:
           context: ./alpine
           dockerfile: Dockerfile
        volumes:
            - 'dash:/opt/dash'
            - './data/uploads:/opt/uploads'
            - 'convert:/opt/convert:z'
        restart: "no"

volumes:
    dash:
    convert:

networks:
    backend:
    
